common: &common
  adapter: sqlite3
  database: db/twitter_topics.db

development:
  <<: *common

production:
  <<: *common

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
